#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $APP_USER WITH PASSWORD '$APP_USER_PWD';
  CREATE DATABASE $APP_DB_NAME OWNER $APP_USER;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_USER;
EOSQL
